name: Test CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        game: ["dstserver", "mcbserver", "mhserver", "terrariaserver", "vhserver"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      
    - name: Run tests
      run: |
        cd ./tests
        go test -v -game '${{ matrix.game }}' -run TestPackerDockerBuild
